### ISSUE TITLE
Dynamic routing does not work without the <Link/> Component

### ISSUE THREAD

**Issue by PuckyEU** [PuckyEU/puckyeu.github.io#15]
Similar:
https://community.cloudflare.com/t/404-when-navigating-directly-to-dynamic-next-js-route/468228 
https://github.com/cloudflare/next-on-pages/issues/32

**Comment by PuckyEU** [comment]
Switched to Vercel, should work now.

**Comment by surjithctly** [comment]
Have the same issue. I have a dead simple setup that includes fallback: true, but its not working.

```
export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true,
  };
}

export async function getStaticProps(context) {
  return {
    props: {},
  };
}
```

**Comment by PuckyEU** [comment]
Does that happen when you run the project in dev mode(`npm run dev`)? Because I found that happening only in production on Github Pages, it did not happen in dev mode. That meant I had to switch to a hosting service that supports dynamic routing, because it seems like Github Pages does not support dynamic routing. I ended up choosing Vercel.

**Comment by surjithctly** [comment]
Cloudflare Pages. Local works fine

**Comment by PuckyEU** [comment]
Cloudflare Pages seems that it should support dynamic routing because they have it in their [Docs](https://developers.cloudflare.com/pages/platform/functions/routing/#dynamic-routes), but others seem to have issues with NextJs dynamic routing on Cloudflare (https://github.com/cloudflare/next-on-pages/issues/32). You can try to read through that, maybe it will help, but I wasn't able to find anything meaningful to me, but it could help you. The other option is to try to host your site on Vercel to see if it works there in production. And if it does work, then you would be sure that it might be an issue on the Cloudflare's end. That would also mean you could switch to Vercel, which helped me, but I'm not sure how viable it would be for you.
